pygments: 	true
markdown: 	maruku
url: "bytespider.github.com/jsOAuth"
navigation:
  - text: "Getting started"
    url: "/"
  - text: "API Reference"
    url: "/api-reference"
  - text: "Index"
    url: "/index"
package_version: 1.3.4