pygments: 	true
markdown: 	maruku
url: "bytespider.github.com/jsOAuth-Manual"
navigation:
  - text: "Getting started"
    url: "index.html"
  - text: "API Reference"
    url: "api-reference"
package_version: 0.10